### ISSUE TITLE
rumah kopetensi

### ISSUE THREAD

**Issue by sanonimus** [microsoft/vscode-edge-devtools#1676]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/1675
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/1673
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/1671
```
