### ISSUE TITLE
.css

### ISSUE THREAD

**Issue by mangarUA** [microsoft/vscode-edge-devtools#1847]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/1846
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/1842
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/1845
```
