### ISSUE TITLE
وم

### ISSUE THREAD

**Issue by mohamed2015ali** [microsoft/vscode-edge-devtools#1913]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/1912
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/1911
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/1620
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/1899
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/1900
```
