### ISSUE TITLE
songsget

### ISSUE THREAD

**Issue by sijso** [microsoft/vscode-edge-devtools#1915]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/1912
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/1620
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/1913
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/1911
```
