### ISSUE TITLE
ewrew

### ISSUE THREAD

**Issue by xiaoji11223** [microsoft/vscode-edge-devtools#2042]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

```[tasklist]
### Tasks
- [ ] iubethao
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2041
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2039
- [ ] wdq
- [ ] https://github.com/microsoft/vscode-edge-devtools/pull/2040
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2028
```

**Comment by xiaoji11223** [comment]
2024年第058期视频猜测（冰原溜滑梯）<div class="title" style="text-align: center;"><br></div><div class="text"><p>狗爸爸带著儿子来到野外学习求生技巧，却遇到饥饿的狮子前来捣乱，究竟是能顺利学习到求生，还是被狮子反扑呢...本期视频会给我们的带了什么样的玄机呢</p></div>

**Comment by vidorteg** [comment]
Hi, please provide feedback in english, it is ok to use a translator and we can try to figure out the details. From what I can tell there is missing information to make this actionable. feel free to reopen if more information is available.
