### ISSUE TITLE
Prosto15

### ISSUE THREAD

**Issue by Prosto15** [microsoft/vscode-edge-devtools#2130]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2128
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2129
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2127
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2126
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2125
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2122
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2123
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2124
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2121
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2120
```
