### ISSUE TITLE
task1

### ISSUE THREAD

**Issue by naagadhepthi-11** [microsoft/vscode-edge-devtools#2166]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

```[tasklist]
### Tasks
- [x] output error. Note opening in the ms edge
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2164
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2139
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2165
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2161
```

**Comment by naagadhepthi-11** [comment]
can you help with local host error and should open in micro soft edge.
