### ISSUE TITLE
DJANGO

### ISSUE THREAD

**Issue by femenza** [microsoft/vscode-edge-devtools#2235]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2231
- [ ] https://github.com/microsoft/vscode-edge-devtools/pull/2234
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/1942
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2233
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2230
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2229
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2226
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2225
```
