### ISSUE TITLE
game code file for shadow fight 2

### ISSUE THREAD

**Issue by chiboy68** [microsoft/vscode-edge-devtools#2379]
[argv.json](https://github.com/user-attachments/files/16738346/argv.json)
[

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2378
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2372
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2374
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2373
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2375
```

```[tasklist]
### Tasks
- [x] not playing on my system
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2378
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2376
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2372
```

**Comment by chiboy68** [comment]
work on the game called shadow fight 2

**Comment by chiboy68** [comment]
please

**Comment by nmba2024414** [comment]
Ok
