### ISSUE TITLE
21@Abhilash j

### ISSUE THREAD

**Issue by Abhilash-21-com** [microsoft/vscode-edge-devtools#2419]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-edge-devtools/pull/2418
- [ ] https://github.com/microsoft/vscode-edge-devtools/pull/2417
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2348
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2390
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-edge-devtools/pull/2234
```
