### ISSUE TITLE
costura

### ISSUE THREAD

**Issue by vegetta77755** [microsoft/vscode-edge-devtools#2439]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2438
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2437
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2148
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2422
```

**Comment by vegetta77755** [comment]
gracias porsus

**Comment by vegetta77755** [comment]
das

**Comment by vidorteg** [comment]
Hi, 
Please add more information and feel free to reopen.
